# Generated by Django 4.2.7 on 2023-11-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='revicer',
            new_name='reciver',
        ),
    ]
