# Generated by Django 4.2.7 on 2023-11-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_revicer_relationship_reciver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='reciver',
            new_name='revicer',
        ),
    ]
